const message={
    _data: {
      id: {
        fromMe: false,
        remote: '8615068879064@c.us',
        id: '3A5E15A916154BEA8B30',
        _serialized: 'false_8615068879064@c.us_3A5E15A916154BEA8B30'
      },
      body: 'cosmétique',
      type: 'buttons_response',
      t: 1667760302,
      notifyName: 'Merveille👸❤️',
      from: '8615068879064@c.us',
      to: '212700480681@c.us',
      self: 'in',
      ack: 1,
      isNewMsg: true,
      star: false,
      kicNotified: false,
      recvFresh: true,
      isFromTemplate: false,
      pollInvalidated: false,
      latestEditMsgKey: null,
      latestEditSenderTimestampMs: null,
      broadcast: false,
      quotedMsg: {
        type: 'chat',
        headerType: 2,
        title: 'Bienvenue !',
        body: "Bonjour! Je suis votre shopping assistant aujourd'hui et je suis là pour vous aider. Voici nos catégories, choisissez la catégorie qui vous intéresse.",
        isDynamicReplyButtonsMsg: true,
        dynamicReplyButtons: [Array],
        caption: "Bonjour! Je suis votre shopping assistant aujourd'hui et je suis là pour vous aider. Voici nos catégories, choisissez la catégorie qui vous intéresse.",
        footer: 'Vous pouvez toujours voir nos catégories avec la commande: !categorie'
      },
      quotedStanzaID: '3EB010A2197CAB1AF460',
      quotedParticipant: '212700480681@c.us',
      mentionedJidList: [],
      isVcardOverMmsDocument: false,
      hasReaction: false,
      ephemeralOutOfSync: false,
      productHeaderImageRejected: false,
      lastPlaybackProgress: 0,
      isDynamicReplyButtonsMsg: false,
      selectedButtonId: '1',
      isMdHistoryMsg: false,
      stickerSentTs: 0,
      isAvatar: false,
      requiresDirectConnection: false,
      pttForwardedFeaturesEnabled: true,
      isEphemeral: false,
      isStatusV3: false,
      links: []
    },
    mediaKey: undefined,
    id: {
      fromMe: false,
      remote: '8615068879064@c.us',
      id: '3A5E15A916154BEA8B30',
      _serialized: 'false_8615068879064@c.us_3A5E15A916154BEA8B30'
    },
    ack: 1,
    hasMedia: false,
    body: 'cosmétique',
    type: 'buttons_response',
    timestamp: 1667760302,
    from: '8615068879064@c.us',
    to: '212700480681@c.us',
    author: undefined,
    deviceType: 'ios',
    isForwarded: undefined,
    forwardingScore: 0,
    isStatus: false,
    isStarred: false,
    broadcast: false,
    fromMe: false,
    hasQuotedMsg: true,
    duration: undefined,
    location: undefined,
    vCards: [],
    inviteV4: undefined,
    mentionedIds: [],
    orderId: undefined,
    token: undefined,
    isGif: false,
    isEphemeral: false,
    links: [],
    selectedButtonId: '1'
  }